version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile # Ensure this matches the Dockerfile name
    ports:
      - "3000:3000" # Expose port for the Node.js application
    privileged: true # Required for Docker-in-Docker
